# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1030ef298ca72de51db287924388c87ddab69841a2169ccff8a6ef732c75177c0e592d83f4a2c3d277e2e1c50f9c7ff37b462dc5f924e837f93ff94403fa05d

test:
  secret_key_base: caaeac4f7abf6626570ceeb7ac3faebe8c167c29a43ef4429e2b902d9d570479266ead847d8532ac18432e2dd9b5f3c8f9e2dfeec276c2aca919d1ae13414bcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
